version: "3"

services:
  zachjustus:
    image: node:18-alpine3.17
    container_name: zjustus
    working_dir: /home/node/app
    entrypoint: ["npm", "start"]
    # environment:
    #   - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - '8080'
    ports:
      - 8080:8080